## Cобственные примеры для каждого из представленных свойств матричных вычислений. 

In [3]:
import numpy as np

#### Транспонирование матрицы

Свойство 1. Дважды транспонированная матрица равна исходной матрице:

In [10]:
A = np.matrix('11 22 33; 44 55 66; 7 3 4')
print('Исходная матрица:\n', A)
print('Первое транспонирование матрицы:\n', A.T)
print('Второе транспонирование матрицы:\n', (A.T).T)

Исходная матрица:
 [[11 22 33]
 [44 55 66]
 [ 7  3  4]]
Первое транспонирование матрицы:
 [[11 44  7]
 [22 55  3]
 [33 66  4]]
Второе транспонирование матрицы:
 [[11 22 33]
 [44 55 66]
 [ 7  3  4]]


Свойство 2. Транспонирование суммы матриц равно сумме транспонированных матриц:

In [11]:
A = np.matrix('5 7 15; 2 33 11; 3 4 1')
print('Матрица А:\n', A)
B = np.matrix('11 22 33; 44 55 66; 7 3 4')
print('Матрица B:\n', B)

L = (A + B).T
print('Транспонирование суммы матриц:\n', L)

R = A.T + B.T
print('Cуммa транспонированных матриц:\n', R)

Матрица А:
 [[ 5  7 15]
 [ 2 33 11]
 [ 3  4  1]]
Матрица B:
 [[11 22 33]
 [44 55 66]
 [ 7  3  4]]
Транспонирование суммы матриц:
 [[16 46 10]
 [29 88  7]
 [48 77  5]]
Cуммa транспонированных матриц:
 [[16 46 10]
 [29 88  7]
 [48 77  5]]


Свойство 3. Транспонирование произведения матриц равно произведению транспонированных
матриц расставленных в обратном порядке:

In [13]:
A = np.matrix('5 7; 2 33')
print('Матрица А:\n', A)
B = np.matrix('11 22; 44 55')
print('Матрица B:\n', B)

L = (A.dot(B)).T
print('Транспонирование произведения матриц:\n', L)

R = (B.T).dot(A.T)
print('Произведение транспонированных матриц'
      'расставленных в обратном порядке:\n', R)

Матрица А:
 [[ 5  7]
 [ 2 33]]
Матрица B:
 [[11 22]
 [44 55]]
Транспонирование произведения матриц:
 [[ 363 1474]
 [ 495 1859]]
Произведение транспонированных матрицрасставленных в обратном порядке:
 [[ 363 1474]
 [ 495 1859]]


Свойство 4. Транспонирование произведения матрицы на число равно произведению этого
числа на транспонированную матрицу:

In [14]:
A = np.matrix('5 7 7; 2 33 7')
k = 2
print('Исходная матрица:\n', A)

L = (k * A).T
print('Транспонирование произведения матрицы на число:\n', L)

R = k * (A.T)
print('Произведение числа на транспонированную матрицу:\n', R)

Исходная матрица:
 [[ 5  7  7]
 [ 2 33  7]]
Транспонирование произведения матрицы на число:
 [[10  4]
 [14 66]
 [14 14]]
Произведение числа на транспонированную матрицу:
 [[10  4]
 [14 66]
 [14 14]]


*Свойство 5*. Определители исходной и транспонированной матрицы совпадают:

In [17]:
A = np.matrix('5 7 7; 2 33 7; 1 2 3')
print('Исходная матрица:\n', A)

A_det = np.linalg.det(A)
print('Определитель исходной матрицы:', format(A_det, '.9g'))

A_T_det = np.linalg.det(A.T)
print('Определитель транспонированной матрицы:', format(A_T_det, '.9g'))

Исходная матрица:
 [[ 5  7  7]
 [ 2 33  7]
 [ 1  2  3]]
Определитель исходной матрицы: 229
Определитель транспонированной матрицы: 229


#### Действия над матрицами

###### Умножение матрицы на число

Свойство 1. Произведение единицы и любой заданной матрицы равно заданной матрице:

In [18]:
A = np.matrix('5 7 7; 2 33 7; 1 2 3')
print('Исходная матрица:\n', A)

L = 1 * A
print('Произведение единицы и матрицы:\n', L)

Исходная матрица:
 [[ 5  7  7]
 [ 2 33  7]
 [ 1  2  3]]
Произведение единицы и матрицы:
 [[ 5  7  7]
 [ 2 33  7]
 [ 1  2  3]]


Свойство 2. Произведение нуля и любой матрицы равно нулевой матрице, размерность которой
равна исходной матрицы:

In [24]:
A = np.matrix('5 7; 2 33')
Z = np.matrix('0 0; 0 0')
print(f"Исходная матрица:\n {A}\n", f"Нулевая матрица:\n {Z}")

L = 0 * A
print('Произведение нуля и матрицы A:\n', L)

Исходная матрица:
 [[ 5  7]
 [ 2 33]]
 Нулевая матрица:
 [[0 0]
 [0 0]]
Произведение нуля и матрицы A:
 [[0 0]
 [0 0]]


Свойство 3. Произведение матрицы на сумму чисел равно сумме произведений матрицы на
каждое из этих чисел:

In [26]:
A = np.matrix('5 7 7; 2 33 7; 1 2 3')
print('Исходная матрица:\n', A)
p, q = 5, 7

L = (p + q) * A
print('Произведение матрицы на сумму чисел:\n', L)

R = p * A + q * A
print('Cуммa произведений матрицы на каждое из чисел:\n', R)

Исходная матрица:
 [[ 5  7  7]
 [ 2 33  7]
 [ 1  2  3]]
Произведение матрицы на сумму чисел:
 [[ 60  84  84]
 [ 24 396  84]
 [ 12  24  36]]
Cуммa произведений матрицы на каждое из чисел:
 [[ 60  84  84]
 [ 24 396  84]
 [ 12  24  36]]


Свойство 4. Произведение матрицы на произведение двух чисел равно произведению второго
числа и заданной матрицы, умноженному на первое число:

In [28]:
A = np.matrix('5 7 7; 2 33 7; 1 2 3')
print('Исходная матрица:\n', A)
p, q = 5, 7

L = (p * q) * A
print('Произведение матрицы на произведение 2-ух чисел:\n', L)

R = p * (q * A)
print('Произведение 2 числа и матрицы, умноженное на 1 число:\n', R)

Исходная матрица:
 [[ 5  7  7]
 [ 2 33  7]
 [ 1  2  3]]
Произведение матрицы на произведение 2-ух чисел:
 [[ 175  245  245]
 [  70 1155  245]
 [  35   70  105]]
Произведение 2 числа и матрицы, умноженное на 1 число:
 [[ 175  245  245]
 [  70 1155  245]
 [  35   70  105]]


Свойство 5. Произведение суммы матриц на число равно сумме произведений этих матриц на
заданное число:

In [29]:
A = np.matrix('5 7; 2 33')
print('Матрица А:\n', A)
B = np.matrix('11 22; 44 55')
print('Матрица B:\n', B)
k = 5

L = k * (A + B)
print('Произведение суммы матриц на число 5:\n', L)

R = k * A + k * B
print('Cуммa произведений этих матриц на число 5:\n', R)

Матрица А:
 [[ 5  7]
 [ 2 33]]
Матрица B:
 [[11 22]
 [44 55]]
Произведение суммы матриц на число 5:
 [[ 80 145]
 [230 440]]
Cуммa произведений этих матриц на число 5:
 [[ 80 145]
 [230 440]]


###### Сложение матриц

Свойство 1. Коммутативность сложения. От перестановки матриц их сумма не изменяется:

In [30]:
A = np.matrix('5 7; 2 33')
print('Матрица А:\n', A)
B = np.matrix('11 22; 44 55')
print('Матрица B:\n', B)

L = A + B
print('Сложение матрицы А и В:\n', L)

R = B + A
print('Сложение матрицы B и A:\n', R)

Матрица А:
 [[ 5  7]
 [ 2 33]]
Матрица B:
 [[11 22]
 [44 55]]
Сложение матрицы А и В:
 [[16 29]
 [46 88]]
Сложение матрицы B и A:
 [[16 29]
 [46 88]]


Свойство 2. Ассоциативность сложения. Результат сложения трех и более матриц не зависит от
порядка, в котором эта операция будет выполняться:

In [32]:
A = np.matrix('5 7; 2 33')
print('Матрица А:\n', A)
B = np.matrix('11 22; 44 55')
print('Матрица B:\n', B)
C = np.matrix('1 3; 3 3')
print('Матрица C:\n', C)

L = A + (B + C)
print('A + (B + C):\n', L)

R = (A + B) + C
print('(A + B) + C:\n', R)

Матрица А:
 [[ 5  7]
 [ 2 33]]
Матрица B:
 [[11 22]
 [44 55]]
Матрица C:
 [[1 3]
 [3 3]]
A + (B + C):
 [[17 32]
 [49 91]]
(A + B) + C:
 [[17 32]
 [49 91]]


Свойство 3. Для любой матрицы существует противоположная ей , такая, что их сумма является
нулевой матрицей :

In [35]:
A = np.matrix('5 7 7; 2 33 7')
print('Исходная матрица:\n', A)
Z = np.matrix('0 0 0; 0 0 0')
print('Нулевая матрица:\n', A)

L = A + (-1)*A
print('Сумма матрицы A и её противоположной матрицы:\n', L)

Исходная матрица:
 [[ 5  7  7]
 [ 2 33  7]]
Нулевая матрица:
 [[ 5  7  7]
 [ 2 33  7]]
Сумма матрицы A и её противоположной матрицы:
 [[0 0 0]
 [0 0 0]]


###### Умножение матриц

Свойство 1. Ассоциативность умножения. Результат умножения матриц не зависит от порядка, в
котором будет выполняться эта операция:

In [38]:
A = np.matrix('5 7; 2 33')
print('Матрица А:\n', A)
B = np.matrix('11 22; 44 55')
print('Матрица B:\n', B)
C = np.matrix('1 3; 3 3')
print('Матрица C:\n', C)

L = A.dot(B.dot(C))
print('A*(B*C)=\n', L)

R = (A.dot(B)).dot(C)
print('(A*B)*C=\n', R)

Матрица А:
 [[ 5  7]
 [ 2 33]]
Матрица B:
 [[11 22]
 [44 55]]
Матрица C:
 [[1 3]
 [3 3]]
A*(B*C)=
 [[1848 2574]
 [7051 9999]]
(A*B)*C=
 [[1848 2574]
 [7051 9999]]


Свойство 2. Дистрибутивность умножения. Произведение матрицы на сумму матриц равно
сумме произведений матриц:

In [39]:
A = np.matrix('5 7; 2 33')
print('Матрица А:\n', A)
B = np.matrix('11 22; 44 55')
print('Матрица B:\n', B)
C = np.matrix('1 3; 3 3')
print('Матрица C:\n', C)

L = A.dot(B + C)
print('Произведение матрицы на сумму матриц:\n', L)

R = A.dot(B) + A.dot(C)
print('Cуммa произведений матриц:\n', R)

Матрица А:
 [[ 5  7]
 [ 2 33]]
Матрица B:
 [[11 22]
 [44 55]]
Матрица C:
 [[1 3]
 [3 3]]
Произведение матрицы на сумму матриц:
 [[ 389  531]
 [1575 1964]]
Cуммa произведений матриц:
 [[ 389  531]
 [1575 1964]]


Свойство 3. Умножение матриц в общем виде не коммутативно. Это означает, что для матриц не
выполняется правило независимости произведения от перестановки множителей:

In [41]:
A = np.matrix('5 7; 2 33')
print('Матрица А:\n', A)
B = np.matrix('11 22; 44 55')
print('Матрица B:\n', B)

L = A.dot(B)
print('Произведение А на В:\n', L)

R = B.dot(A)
print('Произведение В на А:\n', R)

Матрица А:
 [[ 5  7]
 [ 2 33]]
Матрица B:
 [[11 22]
 [44 55]]
Произведение А на В:
 [[ 363  495]
 [1474 1859]]
Произведение В на А:
 [[  99  803]
 [ 330 2123]]


Свойство 4. Произведение заданной матрицы на единичную равно исходной матрице:

In [42]:
A = np.matrix('5 7; 2 9')
print('Матрица А:\n', A)
E = np.matrix('1 0; 0 1')

L = E.dot(A)
print("Произведение единичной матрицы на матрицу А:\n", L)

R = A.dot(E)
print('Произведение матрицы А на единичную:\n', R)

Матрица А:
 [[5 7]
 [2 9]]
Произведение единичной матрицы на матрицу А:
 [[5 7]
 [2 9]]
Произведение матрицы А на единичную:
 [[5 7]
 [2 9]]


Свойство 5. Произведение заданной матрицы на нулевую матрицу равно нулевой матрице:

In [43]:
A = np.matrix('5 7; 2 9')
print('Матрица А:\n', A)
Z = np.zeros((2, 2))

L = Z.dot(A)
print('Произведение матрицы A на нулевую матрицу:\n', L)

R = A.dot(Z)
print('Произведение нулевой матрицы на матрицу А:\n', R)

Матрица А:
 [[5 7]
 [2 9]]
Произведение матрицы A на нулевую матрицу:
 [[0. 0.]
 [0. 0.]]
Произведение нулевой матрицы на матрицу А:
 [[0. 0.]
 [0. 0.]]


#### Определитель матрицы

Свойство 1. Определитель матрицы остается неизменным при ее транспонировании:

In [45]:
A = np.matrix('5 7 4; 2 9 4; 2 1 1 ')
print('Матрица А:\n', A)
print('Транспонированнная матрица А:\n', A.T)

det_A = round(np.linalg.det(A), 3)
print('Определитель исходной матрицы =', det_A)

det_A_t = round(np.linalg.det(A.T), 3)
print('Определитель транспонированной матрицы =', det_A_t)

Матрица А:
 [[5 7 4]
 [2 9 4]
 [2 1 1]]
Транспонированнная матрица А:
 [[5 2 2]
 [7 9 1]
 [4 4 1]]
Определитель исходной матрицы = 3.0
Определитель транспонированной матрицы = 3.0


Свойство 2. Если у матрицы есть строка или столбец, состоящие из нулей, то определитель
такой матрицы равен нулю:

In [46]:
A = np.matrix('5 7 4; 0 0 0; 2 1 1 ')
print('Матрица А:\n', A)

print('Определитель матрицы A =', np.linalg.det(A))

Матрица А:
 [[5 7 4]
 [0 0 0]
 [2 1 1]]
Определитель матрицы A = 0.0


Свойство 3. При перестановке строк матрицы знак ее определителя меняется на
противоположный:

In [47]:
A = np.matrix('9 1 7; 9 6 3; 5 6 1')
print('Матрица А:\n', A)
B = np.matrix('9 1 7; 5 6 1; 9 6 3')
print('Матрица B:\n', B)

print('Определитель матрицы A =', round(np.linalg.det(A), 3))
print('Определитель матрицы B =', round(np.linalg.det(B), 3))

Матрица А:
 [[9 1 7]
 [9 6 3]
 [5 6 1]]
Матрица B:
 [[9 1 7]
 [5 6 1]
 [9 6 3]]
Определитель матрицы A = 66.0
Определитель матрицы B = -66.0


Свойство 4. Если у матрицы есть две одинаковые строки, то ее определитель равен нулю:

In [48]:
A = np.matrix('9 1 7; 9 1 7; 5 6 1')
print('Матрица А:\n', A)

print('Определитель матрицы A =', np.linalg.det(A))

Матрица А:
 [[9 1 7]
 [9 1 7]
 [5 6 1]]
Определитель матрицы A = 0.0


Свойство 5. Если все элементы строки или столбца матрицы умножить на какое-то число, то и
определитель будет умножен на это число:

In [50]:
A = np.matrix('5 7 2; 2 33 1; 7 7 8')
print('Матрица А:\n', A)

k = 5
B = A.copy()
B[2, :] = k * B[2, :]
print('Матрица B, элементы 3 строки которой умножены на число:\n', B)

det_A = round(np.linalg.det(A), 3)
print('Определитель А, умноженный на число =', det_A * k)

det_B = round(np.linalg.det(B), 3)
print('Определитель B', det_B)

Матрица А:
 [[ 5  7  2]
 [ 2 33  1]
 [ 7  7  8]]
Матрица B, элементы 3 строки которой умножены на число:
 [[ 5  7  2]
 [ 2 33  1]
 [35 35 40]]
Определитель А, умноженный на число = 3940.0
Определитель B 3940.0


Свойство 6. Если все элементы строки или столбца можно представить как сумму двух
слагаемых, то определитель такой матрицы равен сумме определителей двух соответствующих
матриц:

In [57]:
A = np.matrix('3 1 1; 5 4 2; 1 1 1')
print('Матрица А:\n', A)
B = np.matrix('3 1 1; 1 2 2; 1 1 1')
print('Матрица B:\n', B)

C = A.copy()
C[1, :] += B[1, :]
print('Матрица С, у которой элементы 2 строки равны'
      'сумме элементов вторых строк матриц А и В', C)

print('Определитель матрицы С =', round(np.linalg.det(C), 2))

print('Сумма определителей матриц А и В =', round(np.linalg.det(A), 2) + round(np.linalg.det(B), 2))

Матрица А:
 [[3 1 1]
 [5 4 2]
 [1 1 1]]
Матрица B:
 [[3 1 1]
 [1 2 2]
 [1 1 1]]
Матрица С, у которой элементы 2 строки равнысумме элементов вторых строк матриц А и В [[3 1 1]
 [6 6 4]
 [1 1 1]]
Определитель матрицы С = 4.0
Сумма определителей матриц А и В = 4.0


Свойство 7. Если к элементам одной строки прибавить элементы другой строки, умноженные на
одно и тоже число, то определитель матрицы не изменится:

In [58]:
A = np.matrix('3 1 1; 5 4 2; 1 1 1')
print('Матрица А:\n', A)

k = 3
B = A.copy()
B[1, :] = B[1, :] + k * B[0, :]
print('Матрица B:\n', B)

print('Определитель матрицы А =', round(np.linalg.det(A), 3))
print('Определитель матрицы В =', round(np.linalg.det(B), 3))

Матрица А:
 [[3 1 1]
 [5 4 2]
 [1 1 1]]
Матрица B:
 [[ 3  1  1]
 [14  7  5]
 [ 1  1  1]]
Определитель матрицы А = 4.0
Определитель матрицы В = 4.0


Свойство 8. Если строка или столбец матрицы является линейной комбинацией других строк
(столбцов), то определитель такой матрицы равен нулю:

In [59]:
A = np.matrix('3 1 1; 5 4 2; 1 1 1')
print('Матрица А:\n', A)

k = 3
A[1, :] = A[0, :] + k * A[2, :]
print('Определитель матрицы А =', round(np.linalg.det(A), 3))

Матрица А:
 [[3 1 1]
 [5 4 2]
 [1 1 1]]
Определитель матрицы А = 0.0


Свойство 9. Если матрица содержит пропорциональные строки, то ее определитель равен нулю:

In [60]:
A = np.matrix('3 1 1; 5 4 2; 1 1 1')
print('Матрица А:\n', A)

k = 3
A[1, :] = k * A[0, :]
print('Матрица А после умножения на k:\n', A)

print('Определитель матрицы А =', round(np.linalg.det(A), 3))

Матрица А:
 [[3 1 1]
 [5 4 2]
 [1 1 1]]
Матрица А после умножения на k:
 [[3 1 1]
 [9 3 3]
 [1 1 1]]
Определитель матрицы А = 0.0


#### Обратная матрица

Свойство 1. Обратная матрица обратной матрицы есть исходная матрица:

In [61]:
A = np.matrix('3. -1.; 11. 1.')
print('Матрица А:\n', A)

A_inv = np.linalg.inv(A)
print('Обратная матрица:\n', A)

A_inv_inv = np.linalg.inv(A_inv)
print('Обратная матрица обратной матрицы:\n', A_inv_inv)

Матрица А:
 [[ 3. -1.]
 [11.  1.]]
Обратная матрица:
 [[ 3. -1.]
 [11.  1.]]
Обратная матрица обратной матрицы:
 [[ 3. -1.]
 [11.  1.]]


Свойство 2. Обратная матрица транспонированной матрицы равна транспонированной матрице
от обратной матрицы:

In [62]:
A = np.matrix('3. -1.; 11. 1.')
print('Матрица А:\n', A)

L = np.linalg.inv(A.T)
print('Обратная матрица транспонированной матрицы:\n', L)

R = (np.linalg.inv(A)).T
print('Транспонированная матрица от обратной матрицы:\n', R)

Матрица А:
 [[ 3. -1.]
 [11.  1.]]
Обратная матрица транспонированной матрицы:
 [[ 0.07142857 -0.78571429]
 [ 0.07142857  0.21428571]]
Транспонированная матрица от обратной матрицы:
 [[ 0.07142857 -0.78571429]
 [ 0.07142857  0.21428571]]


Свойство 3. Обратная матрица произведения матриц равна произведению обратных матриц:

In [63]:
A = np.matrix('3 1; 5 4')
print('Матрица А:\n', A)
B = np.matrix('1 1; 1 2')
print('Матрица B:\n', B)

L = np.linalg.inv(A.dot(B))
print('Обратная матрица произведения матриц:\n', L)

R = np.linalg.inv(B).dot(np.linalg.inv(A))
print('Произведение обратных матриц:\n', R)

Матрица А:
 [[3 1]
 [5 4]]
Матрица B:
 [[1 1]
 [1 2]]
Обратная матрица произведения матриц:
 [[ 1.85714286 -0.71428571]
 [-1.28571429  0.57142857]]
Произведение обратных матриц:
 [[ 1.85714286 -0.71428571]
 [-1.28571429  0.57142857]]
